// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlsTP0Kv19g8FgjbCT02dT7T63SJfkiFw',
    appId: '1:513310229909:web:120a55a2da5997dc05a29c',
    messagingSenderId: '513310229909',
    projectId: 'myheart-688e0',
    authDomain: 'myheart-688e0.firebaseapp.com',
    storageBucket: 'myheart-688e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxdFovfNiIOFuxPf5Z-8qO2iWPgMRZqM',
    appId: '1:513310229909:android:f832187b0f6406ca05a29c',
    messagingSenderId: '513310229909',
    projectId: 'myheart-688e0',
    storageBucket: 'myheart-688e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbNqWOi4EBwun9jCLI5Vr_6PpmzIP7la0',
    appId: '1:513310229909:ios:1c6610fc61eb79ee05a29c',
    messagingSenderId: '513310229909',
    projectId: 'myheart-688e0',
    storageBucket: 'myheart-688e0.appspot.com',
    iosBundleId: 'com.example.myHeart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbNqWOi4EBwun9jCLI5Vr_6PpmzIP7la0',
    appId: '1:513310229909:ios:1c6610fc61eb79ee05a29c',
    messagingSenderId: '513310229909',
    projectId: 'myheart-688e0',
    storageBucket: 'myheart-688e0.appspot.com',
    iosBundleId: 'com.example.myHeart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlsTP0Kv19g8FgjbCT02dT7T63SJfkiFw',
    appId: '1:513310229909:web:120a55a2da5997dc05a29c',
    messagingSenderId: '513310229909',
    projectId: 'myheart-688e0',
    authDomain: 'myheart-688e0.firebaseapp.com',
    storageBucket: 'myheart-688e0.appspot.com',
  );

}